# Generated by Django 3.2.16 on 2023-01-06 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='ddffdfs', upload_to='picture'),
            preserve_default=False,
        ),
    ]
